# permissions for end users to edit backupjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backupjob-editor-role
rules:
- apiGroups:
  - example.com.my.domain
  resources:
  - backupjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.com.my.domain
  resources:
  - backupjobs/status
  verbs:
  - get
