# permissions for end users to view backupjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backupjob-viewer-role
rules:
- apiGroups:
  - example.com.my.domain
  resources:
  - backupjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - example.com.my.domain
  resources:
  - backupjobs/status
  verbs:
  - get
