apiVersion: example.com.my.domain/v1alpha1
kind: BackupJob
metadata:
  name: backupjob-sample
spec:
  # Add fields here
  schedule: "*/1 * * * *"
  startingDeadlineSeconds: 60
  key: abcd
  secret: mysecret
  path: /tmp
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: go-client
            image: hemanrnjn/go-k8s-client
            args:
            - /main
          restartPolicy: OnFailure
